In [2]:
import numpy as np

#Vecteur simple
a = np.array([1,2,3])


#Vecteur dimension 2 
b = np.array([(4.5,5,6), (7,8,9)], dtype=float)

#déterminer le type des éléments du vecteur b
b.dtype

#récupérer le nom du type (comme un label)
b.dtype.name

#changer le type des éléments d'un array
b.astype(type)

#dimension de b
np.shape(b)


#Vecteur de vecteurs 
c = np.array([[(4.5,5,6), (7,8,9)],[(3,2,1),(4,5,6)]] , dtype = float)

#Vecteur null de dim(3,2)
np.zeros((3,4))


#vecteur constitué de 2vecteurs remplis de 1 de dim(3,4)
np.ones((2,3,4),dtype = np.int16)


#Vecteur allant de 10 à 25 (exclu) avec un pas de 5 (le pas par défaut est 1)
d = np.arange(10,25,5)

#on subdivise equitablement l'intervalle [0,2] en 9
np.linspace(0,2,9)


#vecteur de taille (2,2) rempli de 7(voir np.ones/np.zeros)
e = np.full((2,2),7)


#Matrice unité de taille 2
f = np.eye(2)


#matrice de taille (2,2) remplie de nombre aléatoires N(0,1)
np.random.random((2,2))

#création d'un array vide (les valeurs affichées sont arbitraires)
np.empty ((3,2))

array([1, 2, 3])

In [34]:

b.max(axis=0)

array([7., 8., 9.])

In [31]:
b

array([[4.5, 5. , 6. ],
       [7. , 8. , 9. ]])

In [33]:
np.shape(b)

(2, 3)

In [35]:
b.cumsum(axis=1)

array([[ 4.5,  9.5, 15.5],
       [ 7. , 15. , 24. ]])

In [36]:
b.cumsum(axis=0)

array([[ 4.5,  5. ,  6. ],
       [11.5, 13. , 15. ]])

In [37]:
c

array([[[4.5, 5. , 6. ],
        [7. , 8. , 9. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [39]:
 c.sort(axis=0)

In [40]:
c

array([[[3. , 2. , 1. ],
        [4. , 5. , 6. ]],

       [[4.5, 5. , 6. ],
        [7. , 8. , 9. ]]])

In [41]:
 c.sort(axis=1)

In [42]:
c

array([[[3. , 2. , 1. ],
        [4. , 5. , 6. ]],

       [[4.5, 5. , 6. ],
        [7. , 8. , 9. ]]])

In [43]:
np.shape(c)

(2, 2, 3)

In [44]:
np.shape(b)

(2, 3)

In [45]:
b

array([[4.5, 5. , 6. ],
       [7. , 8. , 9. ]])

In [46]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([7. , 5. , 9. , 4.5])

In [47]:
pwd

'C:\\Users\\33751'